// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} targetURL
 * @param {boolean} startNow
 * @returns {$CancellablePromise<string>}
 */
export function AddFile(targetURL, startNow) {
    return $Call.ByID(892384969, targetURL, startNow);
}

/**
 * @param {string} id
 * @param {boolean} removeFile
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTask(id, removeFile) {
    return $Call.ByID(1544167726, id, removeFile);
}

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function GetConfig() {
    return $Call.ByID(711765718).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<($models.DownloadTask | null)[]>}
 */
export function GetTasks() {
    return $Call.ByID(1204771818).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenDownloadsFolder() {
    return $Call.ByID(2768994141);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function OpenFolder(id) {
    return $Call.ByID(1013097048, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function PauseTask(id) {
    return $Call.ByID(4069724315, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ResumeTask(id) {
    return $Call.ByID(1540237670, id);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3440409943, app);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartAll() {
    return $Call.ByID(3450440691);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopAll() {
    return $Call.ByID(432900447);
}

/**
 * @param {$models.Config} config
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConfig(config) {
    return $Call.ByID(1682045727, config);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
const $$createType1 = $models.DownloadTask.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
