// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("download_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_dir"] = "";
        }
        if (!("meta_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["meta_dir"] = "";
        }
        if (!("max_threads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_threads"] = 0;
        }
        if (!("max_concurrent_downloads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_concurrent_downloads"] = 0;
        }
        if (!("proxy_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["proxy_enabled"] = false;
        }
        if (!("proxy_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxy_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class DownloadTask {
    /**
     * Creates a new DownloadTask instance.
     * @param {Partial<DownloadTask>} [$$source = {}] - The source object to create the DownloadTask.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("file_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file_name"] = "";
        }
        if (!("file_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file_path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("downloaded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloaded"] = 0;
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * MB/s
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }
        if (!("eta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eta"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = Status.$zero;
        }
        if (!("threads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["threads"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("parts" in $$source)) {
            /**
             * @member
             * @type {Part[]}
             */
            this["parts"] = [];
        }
        if (!("error_message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error_message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadTask instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadTask}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parts" in $$parsedSource) {
            $$parsedSource["parts"] = $$createField12_0($$parsedSource["parts"]);
        }
        return new DownloadTask(/** @type {Partial<DownloadTask>} */($$parsedSource));
    }
}

export class Part {
    /**
     * Creates a new Part instance.
     * @param {Partial<Part>} [$$source = {}] - The source object to create the Part.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["end"] = 0;
        }
        if (!("downloaded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloaded"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * MB/s
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = Status.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Part instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Part}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Part(/** @type {Partial<Part>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Status = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusQueued: "Queued",
    StatusDownloading: "Downloading",
    StatusPaused: "Paused",
    StatusCompleted: "Completed",
    StatusError: "Error",
};

// Private type creation functions
const $$createType0 = Part.createFrom;
const $$createType1 = $Create.Array($$createType0);
